// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIDCN9UoR4IYHgck4OxB1SooA2mDA6o5k',
    appId: '1:797128906760:web:571ce118fbf1fe12be59bd',
    messagingSenderId: '797128906760',
    projectId: 'kipss-ai',
    authDomain: 'kipss-ai.firebaseapp.com',
    storageBucket: 'kipss-ai.appspot.com',
    measurementId: 'G-6H9NVHT14G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSnk52X_adkEkx_EFGOi6ETZbbv3pZRIo',
    appId: '1:797128906760:android:97b3fe12af1ab02abe59bd',
    messagingSenderId: '797128906760',
    projectId: 'kipss-ai',
    storageBucket: 'kipss-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC3u57RadJGyG55Bb1gc6DRqhxZtEkiBk',
    appId: '1:797128906760:ios:97a36a9405644a93be59bd',
    messagingSenderId: '797128906760',
    projectId: 'kipss-ai',
    storageBucket: 'kipss-ai.appspot.com',
    androidClientId: '797128906760-hvf4nbj6979qb75ge578hmi8facqquip.apps.googleusercontent.com',
    iosClientId: '797128906760-rj71frtovbvravan20vqkmt2fji7df2h.apps.googleusercontent.com',
    iosBundleId: 'com.sekspir.kipss.yapayzeka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC3u57RadJGyG55Bb1gc6DRqhxZtEkiBk',
    appId: '1:797128906760:ios:1852c390fd4c15e9be59bd',
    messagingSenderId: '797128906760',
    projectId: 'kipss-ai',
    storageBucket: 'kipss-ai.appspot.com',
    androidClientId: '797128906760-hvf4nbj6979qb75ge578hmi8facqquip.apps.googleusercontent.com',
    iosClientId: '797128906760-fqanfjdhjvp7caq5o4v1op9s23t8dlvf.apps.googleusercontent.com',
    iosBundleId: 'com.example.kipss',
  );
}
